Changed federated login
equinor/radix-cost-allocation pull request #67
Opened 2022-02-02 11:38 UTC by sveinpj

2022-02-02 14:25 UTC, oleterno-equinor requested changes
Missing the `write-id` permission. 
Also update `deploy-prod-and-playground.yml` to use federated credentials.

2022-02-03 08:35 UTC, oleterno-equinor reviewed
Missing the permission for `deploy-dev.yml`.
Remove the commented code.

2022-02-03 10:09 UTC, oleterno-equinor reviewed
Change the `deploy-docker.yml` to only have one job, similar to [radix-acr-cleanup](https://github.com/equinor/radix-acr-cleanup/blob/master/.github/workflows/build-push.yml) and [radix-velero-plugin](https://github.com/equinor/radix-velero-plugin/blob/master/.github/workflows/push.yaml). 
Using `if`, specify to only push to radixprod ACR if the branch is `release`, as done in radix-velero-plugin.

2022-02-03 15:26 UTC, oleterno-equinor commented on .github/workflows/deploy-dev.yml
>      steps:
Needs the `actions/checkout@v2` step

2022-02-03 15:26 UTC, oleterno-equinor commented on .github/workflows/deploy-dev.yml
> +        with:
Add a descriptive step name

2022-02-03 15:26 UTC, oleterno-equinor commented on .github/workflows/deploy-docker.yml
>        - name: Generate build ID
Move the `Generate build ID` step further up

2022-02-03 15:26 UTC, oleterno-equinor commented on .github/workflows/deploy-docker.yml
> +        if: github.ref == 'refs/heads/master'
This step should run for both master and release, so this `if` can be removed.

2022-02-03 15:26 UTC, oleterno-equinor commented on .github/workflows/deploy-docker.yml
>        - name: Generate build ID
The build ID only needs to be generated once. This step can be removed.

2022-02-03 15:26 UTC, oleterno-equinor commented on .github/workflows/deploy-docker.yml
>            docker build -t radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} .
At this point, the docker image has already been built for both dev and prod.

2022-02-03 15:26 UTC, oleterno-equinor commented on .github/workflows/deploy-docker.yml
>            docker build -t radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} .
At this point, the docker image has already been built for both dev and prod.

2022-02-04 11:33 UTC, oleterno-equinor commented on .github/workflows/deploy-docker.yml
>            az acr login -n radixdev -g common
Either do the ACR login in its own step or do it as part of another step. It should not be performed twice.

2022-02-04 12:47 UTC, oleterno-equinor approved these changes

2022-02-04 12:55 UTC, satr requested changes

2022-02-04 12:55 UTC, satr commented on .github/workflows/build-push.yml
> +          az logout
This should be run only for release
`if: github.ref == 'refs/heads/release'`

2022-02-07 07:27 UTC, merged